services:
  - type: web
    name: survey-readiness
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: PORT
        value: 10000
